function writeRunStatus(context, status)
%WRITERUNSTATUS Persist per-run status and a convenience latest snapshot.

arguments
    context (1, 1) struct
    status (1, 1) struct
end

step1.io.writeJsonAtomic(context.statusPath, status);
latest = struct( ...
    "schema_version", "step1-latest-run-v2", ...
    "run_id", context.runId, ...
    "profile", context.profile, ...
    "status", string(status.status), ...
    "run_status_path", context.statusPath, ...
    "updated_at", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX")));
step1.io.writeJsonAtomic(context.latestStatusPath, latest);
end
